made robust working

diff --git a/bin/simctl b/bin/simctl
--- a/bin/simctl
+++ b/bin/simctl
@@ -1,89 +1,13 @@
 #!/bin/bash
 
-export ROOTDIR=$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)
-cd $ROOTDIR
+export OSUGM_ROOT=$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)
+cd $OSUGM_ROOT
+source lib/helpers.sh
 source lib/osgum.sh
-
-sim_exists () {
-    (ps -ef | grep "$MONO OpenSim.exe" | grep -qv grep) && test -f "$SIMRUN/OpenSim.exe.pid"
-}
-
-do_start () {
-    local cmd logconfig
-    local elapsed=0
-
-    if sim_exists; then
-        error "$MSGSIM is already running. Use `basename $0` '$SIMNAME' console to view it"
-    fi
-
-    # allow user overriding logging options
-    logconfig="$ROOTDIR/lib/conf/OpenSim.exe.config"
-    [[ -f $SIMCONF/OpenSim.exe.config ]] && logconfig="$SIMCONF/OpenSim.exe.config"
-
-    cmd="env LANG=C $MONO OpenSim.exe -inifile=\"$ROOTDIR/lib/conf/OpenSim.ini\" -inidirectory=\"$SIMCONF\" -logconfig=\"$logconfig\""
-
-    echo -n "$MSGSIM starting "
-    if [[ $1 = 'direct' ]]; then
-        cd "$ROOTDIR/opensim/$OSIM_INSTALL/bin"
-        exec $cmd
-    else
-        tmux_new "OS-$SIMNAME" "$PWD" "$0" $SIMNAME direct
-        # wait until OpenSim pid file is created
-        while :
-        do
-            sleep 1
-            elapsed=$((elapsed + 1))
-            echo -n '.'
-            if sim_exists; then
-                echo ' running'
-                return 0
-            elif [[ $elapsed -ge 10 ]]; then
-                echo -e "\n"
-                error "$MSGSIM failed to start within 10 seconds"
-            fi
-        done
-    fi
-}
-
-do_stop () {
-    local elapsed=0
-
-    sim_exists || error "$MSGSIM is not started"
-    if tmux_exists "OS-$SIMNAME"; then
-        echo -n "$MSGSIM stopping "
-        tmux_send "OS-$SIMNAME" quit
-        while :
-        do
-            sleep 2
-            elapsed=$((elapsed + 2))
-            echo -n '.'
-            if ! sim_exists; then
-                echo ' stopped'
-                return 0
-            elif [[ $elapsed -ge 120 ]]; then
-                echo ' too long... killing!'
-                do_kill
-                return 1
-            fi
-        done
-    else
-        erro "$MSGSIM started manually, stop it from the console"
-    fi
-}
-
-do_kill () {
-    local pid="$SIMRUN/OpenSim.exe.pid"
-    if [[ -f $pid ]]; then
-        kill -9 $(cat "$pid")
-        rm "$pid"
-        echo "$MSGSIM killed"
-
-    fi
-}
 
 do_help () {
     cat << EOT
-$(basename $0) {simname} {command} - Controls a simulator instance
+$OSUGM {simname} {command} - Controls a simulator instance
 Where {simname} is the name of the config directory for that instance
 and {command} is one of:
     enable  Enable auto start of the simulator when running the grid
@@ -100,49 +24,79 @@ EOT
 }
 
 # ensure a simulator instance name as been provided
-export SIMNAME="$1"
-if [[ -z $SIMNAME ]] || [[ $# -lt 2 ]]; then do_help; fi
+export OSUGM_SIMNAME="$1"
+if [[ -z $OSUGM_SIMNAME ]] || [[ $# -lt 2 ]]; then
+    do_help
+fi
 shift
 
-export SIMCONF="$CONFDIR/available/$SIMNAME"
-export SIMRUN="$RUNDIR/$SIMNAME"
-mkdir -p "$SIMRUN/log"
-MSGSIM="[$SIMNAME]"
+export OSUGM_SIMCONF="$OSUGM_CONF/available/$OSUGM_SIMNAME"
+export OSUGM_SIMRUN="$OSUGM_RUN/$OSUGM_SIMNAME"
+mkdir -p "$OSUGM_SIMRUN/log"
+msgsim="$OSUGM_SIMNAME"
 
-source "$SIMCONF/instance.conf" || error "Missing file '$SIMCONF/instance.conf'"
-[[ -n $HTTPPORT ]] || error "Missing variable HTTPPORT in '$SIMCONF/instance.conf'"
-export HTTPPORT
+source "$OSUGM_SIMCONF/instance.conf" || error "Missing file '$OSUGM_SIMCONF/instance.conf'"
+[[ -n $OSUGM_SIMPORT ]] || error "Missing variable OSUGM_SIMPORT in '$OSUGM_SIMCONF/instance.conf'"
 
+sim_exists () {
+    (ps -ef | grep "$OSUGM_MONO OpenSim.exe" | grep -qv grep) && test -f "$OSUGM_SIMRUN/OpenSim.exe.pid"
+}
 
 case "$1" in
 enable)
     ;;
 disable)
     ;;
-direct)
-    do_start direct
-    ;;
-start)
-    do_start
+direct|start)
+    if sim_exists; then
+        log warn "$msgsim is already running. Use `basename $0` '$OSUGM_SIMNAME' console to view it"
+        return 0
+    fi
+
+    # allow user overriding logging options
+    logconfig="$OSUGM_LIB/conf/OpenSim.exe.config"
+    if [[ -f $OSUGM_SIMCONF/OpenSim.exe.config ]]; then
+        logconfig="$OSUGM_SIMCONF/OpenSim.exe.config"
+    fi
+
+    cmd="env LANG=C $OSUGM_MONO OpenSim.exe \
+        -inifile=\"$OSUGM_LIB/conf/OpenSim.ini\" \
+        -inidirectory=\"$OSUGM_SIMCONF\" \
+        -logconfig=\"$logconfig\""
+
+    echo -n "$MSGSIM starting "
+    if [[ $1 = 'direct' ]]; then
+        direct_start $msgsim "$OSUGM_EXEC/$OSUGM_OPENSIM/bin" $cmd
+    else
+        screen_start $msgsim sim_exists 10 "$OSUGM_EXEC/$OSUGM_OPENSIM/bin" $cmd
+    fi
     ;;
 stop)
-    do_stop
+    if sim_exists; then
+        log warn "$msgsim is not started"
+        return 0
+    fi
+    if screen_exists "$OSUGM_SIMNAME"; then
+        screen_stop $msgsim sim_exists 120
+    else
+        log warn "$msgsim started manually, stop it from the console"
+    fi
     ;;
 restart)
-    do_stop && do_start
+    $0 stop && $0 start
     ;;
 kill)
-    do_kill
+    kill_pidfile "$OSUGM_SIMRUN/OpenSim.exe.pid"
     ;;
 status)
     if sim_exists; then
-        echo "$MSGSIM running"
+        echo "$msgsim running"
     else
-        echo "$MSGSIM offline"
+        echo "$msgsim offline"
     fi
     ;;
 console)
-    tmux_show "OS-$SIMNAME"
+    screen_attach "$OSUGM_SIMNAME"
     ;;
 *)
     do_help
